language: java

install:
  - ant resolve-ivy-deps
  - ant wpilib-for-ci

script:
  - ant test

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

addons:
  apt:
    packages:
      - python3
